TRAN-8309: Add route icon
Intersection/gtfs-realtime-translators pull request #69
Opened 2024-10-18 13:09 UTC by prafullint

### Description
Add route icon field in intersection proto update the bindings and other modules

### JIRA Ticket
https://intersection-kb.atlassian.net/browse/TRAN-8309

### Describe your changes (features, changes, fixes, etc.)
Update intersection proto file
Update factories 
Added checks on `njt-rails` and `cta-subway`

2024-10-18 16:21 UTC, joshverma requested changes

2024-10-18 16:21 UTC, joshverma commented on gtfs_realtime_translators/bindings/intersection_pb2.py
> +_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
Was this line autogenerated?

2024-10-18 16:21 UTC, joshverma commented on gtfs_realtime_translators/translators/cta_subway.py
> +        route_icon = cls.__get_route_icon(prediction['flags'], prediction['destNm'])
```suggestion
        route_icon = cls.__get_route_icon(prediction['flags'], headsign)
```

2024-10-18 16:21 UTC, joshverma commented on gtfs_realtime_translators/translators/cta_subway.py
> +    def __get_route_icon(cls, flags, destination):
```suggestion
    def __get_route_icon(cls, flags, headsign):
```

2024-10-18 16:21 UTC, joshverma commented on gtfs_realtime_translators/translators/cta_subway.py
> +        if flags == 'H':
We need to ignore case when checking the value.

```
if flags and flags.lower() == 'h'
```

2024-10-18 16:21 UTC, joshverma commented on gtfs_realtime_translators/translators/cta_subway.py
> +        if destination in ["Midway", "O'Hare"]:
We need to ignore case here, too.

```
if headsign and headsign.lower() in ["midway", "o'hare"]:
```

2024-10-18 16:21 UTC, joshverma commented on gtfs_realtime_translators/translators/njt_rail.py
> +                        route_icon = cls.__get_route_icon(item_entry['DESTINATION'])
```suggestion
                        route_icon = cls.__get_route_icon(headsign)
```

2024-10-18 16:21 UTC, joshverma commented on gtfs_realtime_translators/translators/njt_rail.py
> +    def __get_route_icon(cls, destination):
```suggestion
    def __get_route_icon(cls, headsign):
```

2024-10-18 16:23 UTC, joshverma commented
Do you also mind cleaning up the description? `Add route icon field in intersection proto update the bindings and other modules`

2024-10-22 08:49 UTC, prafullint commented on gtfs_realtime_translators/bindings/intersection_pb2.py
> +_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
yes

2024-10-22 14:41 UTC, joshverma approved these changes
Looks good, let's hold off on merging until we test it though.

2024-10-22 16:18 UTC, JorgeBillini approved these changes

2024-10-29 15:35 UTC, joshverma requested changes

2024-10-29 15:35 UTC, joshverma commented on gtfs_realtime_translators/bindings/gtfs-realtime.proto
> +message RouteIconString {
This should be removed.

2024-11-06 17:44 UTC, Dara-Sy approved these changes

2024-11-07 07:57 UTC, merged